### ISSUE TITLE
How to create a dev environment

### ISSUE THREAD

**Issue by Mte90** [aau-zid/BigBlueButton-liveStreaming#134]
There is a way to develop in this project without requiring to record a video?

I am just looking to understand if there is a way to simplify the development on this projects without run docker, ffmpeg and so on.

**Comment by mtsonline** [comment]
could you explain further, what you want to do?

**Comment by Mte90** [comment]
I want to fix the ticket I opened.
As I see now to do changes on this tool I need docker and to see if the code worked I need to record with ffmpeg.
This is not very helpful to test changes so I was looking if there was a more simple way to contribute it as developer on this.

**Comment by mtsonline** [comment]
what ticket are you refering to?
I am not sure I fully understand what you want to do.
Without docker you would have to install a lot of tools manually, how should this help?
Without ffmpeg how would you stream?
What is your goal, exactly as possible?

**Comment by Mte90** [comment]
Sure :-)

https://github.com/aau-zid/BigBlueButton-liveStreaming/issues/95
https://github.com/aau-zid/BigBlueButton-liveStreaming/issues/127

As you can see they are ticket about the stuff showed on BBB and recorded with ffmpeg. 
So to me they are just css tricks to enable but if I need docker to connect to an external instance and record a video it is kind of a long process to debug them.

Also if there is something simpler I can do also other improvements etc.

**Comment by mtsonline** [comment]
ah, now I understand better what your problem is. :-)

good, a few thoughts on that:

* for testing you do not need docker at all. You always can just use the get_join_url function and experiment there with new parameters. The url can be opened in any browser to see the results. You do not have to open through the streaming docker environment.
* you will have to find a solution how to change something during a meeting via selenium. To test how / what to do with selenium you can do that outside the docker too. Just have a look at selenium and learn how to use this for your goals. I am not sure if it is possible or easy to do that during the session at all.

* css styles won't be changeable during a meeting - this is something for opening a new meeting with some layout. To change during the meeting you need other solutions - see above.

hope this helps a bit ...?
cheers

**Comment by Mte90** [comment]
So to understand:

- Get the url from https://github.com/aau-zid/BigBlueButton-liveStreaming/blob/0f6be59a03b00130a1ff4b7b2cb5a978248ba223/stream.py#L215
- Try the url it in a browser
- Try the url on Selenium 
- Trick selenium with python to do screenshots

So I think that I need a new python script to do all of that.

**Comment by mtsonline** [comment]
why don't you want to use the dockericed setup? if you checkout the git repo and use the docker-compose example with build instead of the image one, you just can edit the lines locally in the python file.
after changing just restart the docker with build flag 
docker-compose stop
docker-compose up --build -d
and the changes should be reflected.

I do not see a need for a separate dev environment

**Comment by Mte90** [comment]
I see that this stream.py file calls ffmpeg so I need to do some changes.
Anyway I don't use Docker and I prefer to have everything on the machine to speed up also.

I will keep you updated about my progress.

**Comment by mtsonline** [comment]
without ffmpeg the whole tool would do nothing?!? What do you want to do without it? you would not get any file to store or stream to send via the network?

If you do not use docker you will never have the same versions of all components for each user and this may cause issues.

looking forward to your experiences and feedback 
good luck

**Comment by Mte90** [comment]
Just in case for someone else that is looking to this.

On stream.py on the stream method you can add a code like this:

```

    global browser
    browser.save_screenshot("./screenshot.png")
    time.sleep(5)
    browser.save_screenshot("./screenshot2.png")
```
So you will get some screenshots
