### ISSUE TITLE
Stream stops & latency

### ISSUE THREAD

**Issue by zihniartar** [aau-zid/BigBlueButton-liveStreaming#72]
Hello,

thanks for the great tool!

My stream regularly breaks off after 50 minutes or sometimes a little later. What could be the reason for that?

I stream on Youtube. The meeting in BBB is still running, but the livestream on Youtube is interrupted. How can I continue the livestream without interrupting the meeting?

And then I wanted to ask that the stream to Youtube has a latency of 5-7 seconds. Is that normal?

Thanks for your answers.

kind regards,
Zihni

**Comment by mtsonline** [comment]
Hi,

if it stopps, you may have to less resources, cpu or memory most likely. There is no maximum limit - so if everything works as expected you could stream until you stop it manually.

You can just restart the docker container with docker-compose stop followed by docker-compose up -d to restart the live stream. there is no need to quit the meeting for that.
Yes, the latency is normal. 5 to 7 seconds is quite good :-)
Every rtmp stream has a higher latency than the direct webrtc streams have, due to transcoding.

hth
Martin
