### ISSUE TITLE
Is this a scalable solution?

### ISSUE THREAD

**Issue by ahmafi** [aau-zid/BigBlueButton-liveStreaming#82]
In our company, we want to stream hundreds of BBB sessions. Can we run multiple instances of this code on a server? The bigger question that I couldn't find it's answer is that is screen recording a scalable solution?

**Comment by mtsonline** [comment]
you can scale this - but I don't know how many instances you can run on one single server.
If you need houndreds of sessions streamed it would defenitely be necessary to have more servers.
Keep in Mind, that you will have to change the ports of liveStreaming if you need multiple instances on one server.

how many sessions do you have on one bbb server? Maybe it makes sense to have one streaming server for each bbb server.

Anyway, scaling is possible. If you need a really large envirionment you should considder load balancing or cdn in addition.
hth

**Comment by ahmafi** [comment]
Should we create a different display server?
I was wondering if there are any limits within x server, like the maximum number of displays you can create. But I couldn't find any limits yet.

**Comment by mtsonline** [comment]
...will close this one, as no comments or ideas came up and it is not directly related - if you find any improvements or answers feel free to add them here - thanks

**Comment by fandigunawan** [comment]
I would suggest create a master that control the streaming service. This master start and stop docker container of streaming service. Another modification on BigBlueButton web frontend is necessary so that the master could be contacted. 

![image](https://user-images.githubusercontent.com/10239907/154496897-a9ee8b67-5e61-4657-b6d0-4f657e490829.png)
